# Лабораторна робота "Операції над масивами NumPy"

__Метою__ лабораторної роботи є набуття практичних навичок та закріплення теоретичних знань по обробці великих однорідних наборів даних які розташовані у вигляді масивів бібліотеки __NumPy__.

Виконати послідовно завдання в секціях, попередню засвоївши наведені приклади
В завданнях продовжити написання коду замість `...`. 

__Імена змінних в завданнях змінювати не можна!__

### Предвстановлення

In [1]:
# Імпортувати бібліотеку numpy з аліасом np
import numpy as np

In [2]:
# Вивід таблиці відповідності кодів типів даних в NumPy
import pandas as pd
dtypes = pd.DataFrame(
    {
        'Type': ['int8', 'uint8', 'int16', 'uint16', 'int32', 'uint32', 'int64', 'uint64', 'float16', 'float32', 'float64', 'float128', 'complex64', 'complex128', 'bool', 'object', 'string_', 'unicode_'],
        'Type Code': ['i1', 'u1', 'i2', 'u2', 'i4', 'u4', 'i8', 'u8', 'f2', 'f4 or f', 'f8 or d', 'f16 or g', 'c8', 'c16', '', 'O', 'S', 'U']
    }
)

dtypes

Type Type Code
0         int8        i1
1        uint8        u1
2        int16        i2
3       uint16        u2
4        int32        i4
5       uint32        u4
6        int64        i8
7       uint64        u8
8      float16        f2
9      float32   f4 or f
10     float64   f8 or d
11    float128  f16 or g
12   complex64        c8
13  complex128       c16
14        bool          
15      object         O
16     string_         S
17    unicode_         U

## 1. Створення та інспектування _np-массивів_

### ПРИКЛАДИ

In [3]:
# Створити 1-вимірний масив з 5 цілочисельних елементів 
arr = np.array([23, 42, 13, 7, 0])

In [4]:
# Інспектування массива
np.info(arr)

class:  ndarray
shape:  (5,)
strides:  (4,)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x2ce006e8ce0
byteorder:  little
byteswap:  False
type: int32


In [5]:
# створити 2-мірний масив з цілим типом даних у 2-х байтовому форматі
arr = np.array([[1,2,3], [4,5,6]], dtype='i2')
print(arr)

[[1 2 3]
 [4 5 6]]


In [6]:
# створити масив із  значень в інтервалі 0 - 20 з кроком 2
# np.arange(start, stop, step)
arr = np.arange(0, 20, 2)  
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [7]:
# створити масив із 20 рівномірно розміщених значень в інтервалі 0 - 10 
# np.linspace(start, stop, num_of_elements) 
arr = np.linspace(0, 10, 20)
print(arr)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [8]:
# створити масив 3х3 випадкових значень 
arr = np.random.rand(3, 3)
print(arr)

[[0.38478196 0.17614738 0.87718048]
 [0.12574964 0.22561981 0.38085741]
 [0.18081994 0.09898419 0.74720479]]


In [9]:
# створення нульвих, одиничних та заповнених масивів
zeros = np.zeros((2,3), dtype='i4')
print(zeros)
ones = np.ones((2,3))
print(ones)
filled = np.full((2,3), 123)
print(filled)

[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[123 123 123]
 [123 123 123]]


In [10]:
print(arr, end="\n...\n")
# інспектування типу массиву `dtype`
print(arr.dtype)
# інспектування розмірності массиву `shape`
print(arr.shape)
# інспектування довжини масиву `len`
print(len(arr))
# інспектування кількості вимірів масиву `ndim`
print(arr.ndim)
# інспектування кількості елементів в масиві `size`
print(arr.size)
# інспектування коількості байтів на елемент `itemsize`
print(arr.itemsize)
# інспектування кількості пам'яти під масив `nbytes`
print(arr.nbytes)

[[0.38478196 0.17614738 0.87718048]
 [0.12574964 0.22561981 0.38085741]
 [0.18081994 0.09898419 0.74720479]]
...
float64
(3, 3)
3
2
9
8
72


In [11]:
arr.__sizeof__()

192

### ЗАВДАННЯ 1

In [16]:
### ЗАВДАННЯ 1.1: створити та проінспектувати масив 3х4 з ім'ям arr1_1, який містить числа з плавоючою точкою 
arr1_1 = np.random.rand(3, 4)
np.info(arr1_1)
print(arr1_1) 

class:  ndarray
shape:  (3, 4)
strides:  (32, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x2ce7ea257c0
byteorder:  little
byteswap:  False
type: float64
[[0.0958495  0.14555435 0.67879483 0.59238325]
 [0.42410208 0.2933958  0.43846475 0.20559269]
 [0.33008723 0.87644208 0.48659925 0.06128113]]


In [17]:
### ЗАВДАННЯ 1.2: створити одномірний масив з 5 строкових елементів
arr1_2 = np.array(['three', 'fifteen', 'find', 'missing', 'teen'])
print(arr1_2)

['three' 'fifteen' 'find' 'missing' 'teen']


In [18]:
### ЗАВДАННЯ 1.3: створити одиничний масив 3х4 чисел з плаваючою точкою
arr1_3 = np.ones((3,4), dtype='f')
print(arr1_3)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## 2. Перетворення форми та типу массивів

### ПРИКЛАДИ

In [12]:
# створити 2-мірний float-масив (2х5) з лінійного int-списка 
spisok = list(range(0,10))
arr = np.array(spisok)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [13]:
#преретворити форму масива `reshape` 
arr = arr.reshape((2,5))
print(arr)
print(arr.dtype)

[[0 1 2 3 4]
 [5 6 7 8 9]]
int32


In [14]:
# -- 3 перетворити тип масива `astype`
arr = arr.astype('float64')
print(arr)
print(arr.dtype)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
float64


In [15]:
# 'вирівняти' 2-мірний масив
arr = arr.flatten()
print(arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### ЗАВДАННЯ 2

In [19]:
### ЗАВДАННЯ 2.1: створити 3-мірний масив (3х1х3) логічного 'False'
arr2_1 = np.array(["False"] * 9)
arr2_1 = arr2_1.reshape((3,1,3))
print(arr2_1)

[[['False' 'False' 'False']]

 [['False' 'False' 'False']]

 [['False' 'False' 'False']]]


In [20]:
### ЗАВДАННЯ 2.2: перетворити масив arr2_1 в 2-мірний масив (3х3) типу int
arr2_2 = arr2_1.reshape((3,3))
...
print(arr2_2)

[['False' 'False' 'False']
 ['False' 'False' 'False']
 ['False' 'False' 'False']]


In [21]:
### ЗАВДАННЯ 2.3: створити  2-мірний масив парних чисел в інтервалі 10-21
parni = []

for i in range(10, 21):
    if i % 2 == 0:
        parni.append(i)
        
arr2_3 = np.array(parni)
arr2_3 = arr2_3.reshape((2,3))
print(arr2_3)

[[10 12 14]
 [16 18 20]]


## 3. Доступ до  елементів масива

### ПРИКЛАДИ

In [22]:
arr = np.array([10, 6, 7, 21, 44]) 
print(arr)

# 1-й елемент 
print(arr[0])
# 3-й елемент
print(arr[2])
# останній елемент
print(arr[-1])

[10  6  7 21 44]
10
7
44


In [23]:
# створити 2-мірний масив з цілих чисел з інтервалу 10-50
arr = np.random.randint(10, 50, (4,4))
print(arr)

[[34 20 45 41]
 [14 41 41 25]
 [43 31 43 47]
 [49 49 42 34]]


In [24]:
# отримати значення останнього елемента в 2 рядку
el = arr[1, -1]
print(el)

25


In [25]:
# отримати значення останнього рядка
vect = arr[-1]
print(vect)

[49 49 42 34]


In [26]:
# отримати `зріз` з 1 по 2 рядок
mat = arr[0:2]
print(mat)

[[34 20 45 41]
 [14 41 41 25]]


In [27]:
# вилучити 2 та 3 стовбчики `arr`
mat = arr[0:4, 1:3]
print(mat)

[[20 45]
 [41 41]
 [31 43]
 [49 42]]


In [28]:
# вилучити непарні рядки `arr`
mat = arr[0:4:2]
print(mat)

[[34 20 45 41]
 [43 31 43 47]]


In [29]:
# фільтрувати елементи масива за умовою
els = arr[arr > 20]
print(els)

[34 45 41 41 41 25 43 31 43 47 49 49 42 34]


### ЗАВДАННЯ 3

In [52]:
### ЗАВДАННЯ 3.1: створити масив 4х5 нормально розподілений випадкових чисел 3 інтервалу [10 - 100]
arr3_1 = np.linspace(10, 100, 20)
arr3_1 = arr3_1.reshape(4,5)
print(arr3_1)

[[ 10.          14.73684211  19.47368421  24.21052632  28.94736842]
 [ 33.68421053  38.42105263  43.15789474  47.89473684  52.63157895]
 [ 57.36842105  62.10526316  66.84210526  71.57894737  76.31578947]
 [ 81.05263158  85.78947368  90.52631579  95.26315789 100.        ]]


In [53]:
### ЗАВДАННЯ 3.2:  вивести 3-елемент в 2-му рядку
el3_2 = arr3_1[1, 2]
print(el3_2)

43.1578947368421


In [54]:
### ЗАВДАННЯ 3.3:  вивести 2-й рядок масива `arr3_1`
vect3_3 = arr3_1[1]
print(vect3_3)

[33.68421053 38.42105263 43.15789474 47.89473684 52.63157895]


In [56]:
### ЗАВДАННЯ 3.4:  вивести 3 колонку масива `arr3_1`
vect3_4 = arr3_1[:, 2]
print(vect3_4)

[19.47368421 43.15789474 66.84210526 90.52631579]


In [57]:
### ЗАВДАННЯ 3.5: вивести матрицю  з 2 та 3 рядка та 2 та 3 колонки масива `arr3_1`
mat3_5 = arr3_1[1:3, 1:3]
print(mat3_5)

[[38.42105263 43.15789474]
 [62.10526316 66.84210526]]


## 4. Матричні компоненти масива

### ПРИКЛАДИ

In [30]:
# створити одиничну матрицю розміру 3х3
mat = np.eye(3)
print(mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [31]:
# створити матрицю із заданою диагоналлю
mat = np.diag([1,2,3,4,5])
print(mat)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [32]:
# вилучити головну діагональ матриці `diag`
mat = np.random.rand(5,5)
print(mat, end="\n...\n")
print(np.diag(mat))

[[0.8141514  0.00554691 0.99543005 0.03572376 0.22965384]
 [0.93897791 0.93801154 0.36177069 0.75092488 0.98414755]
 [0.95630634 0.53205747 0.88143796 0.32640865 0.06881787]
 [0.15518251 0.82311351 0.63688225 0.04731389 0.04044181]
 [0.85483885 0.48822597 0.74694485 0.65336022 0.34436504]]
...
[0.8141514  0.93801154 0.88143796 0.04731389 0.34436504]


In [33]:
# транспонувати матрицю `mat` (https://ru.wikipedia.org/wiki/Транспонированная_матрица)
mT = np.transpose(mat)
print(mT)

[[0.8141514  0.93897791 0.95630634 0.15518251 0.85483885]
 [0.00554691 0.93801154 0.53205747 0.82311351 0.48822597]
 [0.99543005 0.36177069 0.88143796 0.63688225 0.74694485]
 [0.03572376 0.75092488 0.32640865 0.04731389 0.65336022]
 [0.22965384 0.98414755 0.06881787 0.04044181 0.34436504]]


In [34]:
# отримати детермінант матриці `det` (https://ru.wikipedia.org/wiki/Определитель)
print(np.linalg.det(mat))

-0.14329488968423199


In [35]:
# отримати зворотню матриці `det` (https://ru.wikipedia.org/wiki/Обратная_матрица)
invM = np.linalg.inv(mat)
print(invM)

[[-0.31244158  0.603387    2.61295898 -1.25283285 -1.89107433]
 [-0.72713559  0.41135975  0.96477041  0.70020664 -0.9657202 ]
 [ 0.99866955 -0.67680163 -1.67341026  0.96270855  1.48955663]
 [-0.8672629  -0.80240851 -1.25806099 -0.12780061  3.13796138]
 [ 1.28578     0.90938421 -1.83750542  0.2715745  -0.21716001]]


### ЗАВАДАННЯ 4

In [58]:
# ЗАВДАННЯ 4.1: створити квадратну матрицю з 36 рівномірно розподілених цілих 
# елементів з інтервалу 100 - 200
mat4_1 = np.linspace(100, 200, 36)
mat4_1 = mat4_1.reshape(6,6)
print(mat4_1)

[[100.         102.85714286 105.71428571 108.57142857 111.42857143
  114.28571429]
 [117.14285714 120.         122.85714286 125.71428571 128.57142857
  131.42857143]
 [134.28571429 137.14285714 140.         142.85714286 145.71428571
  148.57142857]
 [151.42857143 154.28571429 157.14285714 160.         162.85714286
  165.71428571]
 [168.57142857 171.42857143 174.28571429 177.14285714 180.
  182.85714286]
 [185.71428571 188.57142857 191.42857143 194.28571429 197.14285714
  200.        ]]


In [59]:
# ЗАВДАННЯ 4.2: вивести головну діагональ матниці `mat4_1`
diag4_2 = np.diag(mat4_1)
print(diag4_2)

[100. 120. 140. 160. 180. 200.]


In [60]:
# ЗАВДАННЯ 4.3: транспонувати матрицю 'mat4_1'
trans4_3 = np.transpose(mat4_1)
print(trans4_3)

[[100.         117.14285714 134.28571429 151.42857143 168.57142857
  185.71428571]
 [102.85714286 120.         137.14285714 154.28571429 171.42857143
  188.57142857]
 [105.71428571 122.85714286 140.         157.14285714 174.28571429
  191.42857143]
 [108.57142857 125.71428571 142.85714286 160.         177.14285714
  194.28571429]
 [111.42857143 128.57142857 145.71428571 162.85714286 180.
  197.14285714]
 [114.28571429 131.42857143 148.57142857 165.71428571 182.85714286
  200.        ]]


In [61]:
# ЗАВДАННЯ 4.4: вирахувати зворотню до 'mat4_1' матрицю 
inv4_4 = np.linalg.inv(mat4_1)
inv4_4

array([[ 1.78554566e+13, -3.15844940e+13, -6.83261572e+11,
         2.44413461e+13, -9.77221433e+12, -2.56832740e+11],
       [ 3.23542498e+13, -3.98360239e+13, -1.09998728e+12,
        -8.30858945e+12,  1.74899872e+13, -5.99636367e+11],
       [ 2.71024864e+13, -1.27314587e+13, -4.73868024e+11,
        -3.44624185e+13, -1.42401563e+13,  3.48054151e+13],
       [-2.45059348e+14,  3.27392644e+14, -2.80666284e+13,
        -1.31068963e+13,  2.61398407e+13, -6.72996122e+13],
       [ 1.90116954e+14, -2.99324346e+14,  6.53711179e+13,
         4.06286755e+13, -3.06580895e+13,  3.38656884e+13],
       [-2.23697992e+13,  5.60836790e+13, -3.50473726e+13,
        -9.19211739e+12,  1.10406323e+13, -5.15022152e+11]])

## 5. Операції над масивами

### ПРИКЛАДИ

In [36]:
# задати вектор з 10 елементів
vect = np.array([1, 3, 2, -3, 5, 0])

In [37]:
# вирахувати суму елеметнів
s = np.sum(vect)

# знайти мінімальний ел-т
m = np.min(vect)

# відсортувати вектор по зростанню
vs = np.sort(vect)

# знайти середнє значення
mid = np.average(vect)
...

Ellipsis

In [38]:
# матриця 3х3 сконструйована різними методами
mat = np.array([np.arange(1,4), [-2, 4, 6], np.full(3,77)])
print(mat)

[[ 1  2  3]
 [-2  4  6]
 [77 77 77]]


In [39]:
# сума по колонкам `axis=0`
s = np.sum(mat, axis=0)
print(s)

[76 83 86]


In [40]:
# мінімум по рядкам
m = np.min(mat, axis=1)
print(m)

[ 1 -2 77]


In [41]:
# збільшити ел-ти масива вдвічі
v2 = mat * 2
print(v2)

[[  2   4   6]
 [ -4   8  12]
 [154 154 154]]


In [42]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
N = np.array([[1,1,1],[2,2,2],[3,3,3]])
print(M, N, sep="\n")

[[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]
[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [43]:
# перемножити елементи матриць M, N
K = M * N
print(K)
# або ->
K = np.multiply(N, M)
print(K)

[[ 1  2  3]
 [ 8 -6 12]
 [21 24  0]]
[[ 1  2  3]
 [ 8 -6 12]
 [21 24  0]]


In [62]:
# поелементний поділ
K = N / M
print(K)

[1. 1. 1. 1. 1.]


In [45]:
# скалярне множення матриць (https://ru.wikipedia.org/wiki/Умножение_матриц)
prod = np.dot(N, M)
print(prod)

[[12  7  9]
 [24 14 18]
 [36 21 27]]


In [46]:
# возвести матрицю `prod` в ступінь 3
pmat = np.linalg.matrix_power(prod, 3)
print(pmat)

[[ 33708  19663  25281]
 [ 67416  39326  50562]
 [101124  58989  75843]]


In [47]:
# додати елементи до 1-вимірного масива
mat = np.array([1,2,3])
mat = np.append(mat, [5,6,7,8])
print(mat)

[1 2 3 5 6 7 8]


In [48]:
# вставити елемент `4` в масив після 3-го елемента
mat = np.insert(mat, 3, 4)
print(mat)

[1 2 3 4 5 6 7 8]


In [49]:
# видалити елемент з індексом 6
mat = np.delete(mat, 6)
print(mat)

[1 2 3 4 5 6 8]


In [50]:
#  копіювання та присвоювання масивів
M = np.random.randint(1, 10, 5 )
print(M)

# присвоїти масив `M` в `N`
N = M
print(N)
print(id(M), id(N))

# копіювати масив `M` в `K`
K = np.copy(M)
print(K)
print(id(M), id(K))

[2 3 3 3 9]
[2 3 3 3 9]
3083816458736 3083816458736
[2 3 3 3 9]
3083816458736 3085926590384


In [51]:
# конкатенація масивів по рядкам
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])
arr3 = np.concatenate((arr1, arr2), axis=0)
print(arr3)
# по колонкам `axis = 1`
arr4 = np.concatenate((arr1, arr2), axis=1)
print(arr4)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]
[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### ЗАВДАННЯ 5

In [63]:
# ЗАВДАННЯ 5.1: просумувати по рядкам масив випадкових чисел розмірностю 3х4
mat5_1 = np.random.rand(5,5)
print(mat5_1)
sum_mat5_1 = np.sum(mat5_1, axis=1)
print(sum_mat5_1)

[[0.31285406 0.03155874 0.59207473 0.988086   0.28289903]
 [0.77439267 0.95046372 0.14394325 0.38953548 0.72031549]
 [0.13988517 0.03037095 0.87845692 0.12145022 0.39316221]
 [0.91313075 0.61747924 0.53094953 0.37227264 0.59330715]
 [0.01805506 0.61553721 0.75518673 0.43762264 0.21092683]]
[2.20747256 2.97865061 1.56332547 3.02713931 2.03732847]


In [64]:
# ЗАВДАННЯ 5.2: знайти мінімальний елемент матриці `sum_mat5_1`
min_mat5_1 = np.min(sum_mat5_1)
print(min_mat5_1)

1.5633254715625817


In [65]:
# ЗАВДАННЯ 5.3: створити масив додавши до елементів `mat5_1`  число 100
mat5_3 = mat5_1 + 100
print(mat5_3)

[[100.31285406 100.03155874 100.59207473 100.988086   100.28289903]
 [100.77439267 100.95046372 100.14394325 100.38953548 100.72031549]
 [100.13988517 100.03037095 100.87845692 100.12145022 100.39316221]
 [100.91313075 100.61747924 100.53094953 100.37227264 100.59330715]
 [100.01805506 100.61553721 100.75518673 100.43762264 100.21092683]]


In [66]:
# ЗАВДАННЯ 5.4: помножити матрицю `mat5_1` на головну діагональ матриці `mat5_3`
mat5_4 = np.multiply(mat5_1, np.diag(mat5_3))
print(mat5_4)

[[31.38328375  3.18586932 59.72758515 99.17643745 28.34957352]
 [77.68153908 95.94975325 14.52077343 39.09856152 72.18348237]
 [14.03228033  3.06596143 88.61737847 12.19023476 39.39914992]
 [91.59875187 62.33481602 53.56136922 37.36585055 59.45585918]
 [ 1.81115452 62.1387671  76.18207186 43.92517857 21.13717344]]


In [67]:
# ЗАВДАННЯ 5.5: додати справа до матриці `mat5_3` матрицю `mat5_4` 
# вивести ранг отриманої матриці
mat5_5 = np.concatenate((mat5_3, mat5_4), axis=1)
print(mat5_5)
print(np.linalg.matrix_rank(mat5_5))

[[100.31285406 100.03155874 100.59207473 100.988086   100.28289903
   31.38328375   3.18586932  59.72758515  99.17643745  28.34957352]
 [100.77439267 100.95046372 100.14394325 100.38953548 100.72031549
   77.68153908  95.94975325  14.52077343  39.09856152  72.18348237]
 [100.13988517 100.03037095 100.87845692 100.12145022 100.39316221
   14.03228033   3.06596143  88.61737847  12.19023476  39.39914992]
 [100.91313075 100.61747924 100.53094953 100.37227264 100.59330715
   91.59875187  62.33481602  53.56136922  37.36585055  59.45585918]
 [100.01805506 100.61553721 100.75518673 100.43762264 100.21092683
    1.81115452  62.1387671   76.18207186  43.92517857  21.13717344]]
5
